//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRA.DataProvider.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DRAContext : DbContext
    {
        public DRAContext()
            : base("name=DRAContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompetenciesJob> CompetenciesJobs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<UserCompetencyMatrix> UserCompetencyMatrices { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<JobCompetencyMatrix> JobCompetencyMatrices { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<OnlineAssessmentUser> OnlineAssessmentUsers { get; set; }
        public virtual DbSet<UserRisk> UserRisks { get; set; }
        public virtual DbSet<UserAnswer> UserAnswers { get; set; }
        public virtual DbSet<UserImage> UserImages { get; set; }
    }
}
