//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRA.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public byte JobID { get; set; }
        public string JobTitle { get; set; }
        public string JobBand { get; set; }
    }
}
