//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRA.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCompetencyMatrix
    {
        public int JobID { get; set; }
        public string Type { get; set; }
        public string Maingroup { get; set; }
        public string Subgroup { get; set; }
        public string Competency { get; set; }
        public byte LoW { get; set; }
        public int RequiredLevel { get; set; }
    }
}
