//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRA.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAnswer()
        {
            this.UserImages = new HashSet<UserImage>();
        }
    
        public int UserAnswerId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AssesmentDate { get; set; }
        public int RiskId { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public int Score { get; set; }
        public System.Guid TestIdentifier { get; set; }
    
        public virtual OnlineAssessmentUser OnlineAssessmentUser { get; set; }
        public virtual Question Question { get; set; }
        public virtual Risk Risk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserImage> UserImages { get; set; }
    }
}
