//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRA.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int UserAnswerId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AssesmentDate { get; set; }
        public int RiskId { get; set; }
        public int QuestionId { get; set; }
        public string Answer { get; set; }
        public int Score { get; set; }
    
        public virtual OnlineAssessmentUser OnlineAssessmentUser { get; set; }
        public virtual Question Question { get; set; }
        public virtual Risk Risk { get; set; }
    }
}
