//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRA.DataProvider.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public int UserImageID { get; set; }
        public int UserAnswerID { get; set; }
        public string ImageFileName { get; set; }
    
        public virtual UserAnswer UserAnswer { get; set; }
    }
}
